name: Publish to PyPI

on:
  release:
    types: [published]
    tags:
      - 'v*.*.*'  # Only trigger on version tags

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim  # Using slim image for smaller footprint
    
    # Additional safety check
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: poetry install --with dev
    - name: Build and publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry build
        poetry publish
