name: Publish to PyPI

on:
  release:
    types: [published]
    tags:
      - 'v*.*.*'  # Only trigger on version tags

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim  # Using slim image for smaller footprint
    
    # Additional safety check
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Build package
      run: python -m build
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
