name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11  # Cannot use slim as we need TK
    strategy:
      matrix:
        python-version: ["3.11"]  # Reduced to single latest version

    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y xvfb
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run tests with coverage
      run: |
        xvfb-run pytest --cov=declutrr --cov-report=xml --cov-report=term
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
